name: "Character Problem"
description: "Request a certain character be fixed"
title: "[Character Problem] <title>"
labels: ["character problem"]
assignees:
  - trip5
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to give feedback!
        
        If you can, submit a pixel pic to be more precise: [`Pixel Editor`] (https://pixieengine.com/pixel-editor) is good.  Then attach a picture to your report.
  - type: textarea
    id: info
    attributes:
    label: Information
    description: |
      A quick description and some sample letters would be good.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true