name: Language Request
description: Request a new language be added
title: "[Language Request] <title>"
labels: ["language request"]
assignees:
  - trip5
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to give feedback!
        
        I will do my best to add your language but be aware that I will probably ask you more questions!
  - type: textarea
    id: info
    attributes:
    label: Information
    description: |
      A quick description and some sample letters would be good.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true