name: "Other"
description: "Got something positive to say?"
title: "[Positive Vibes] <title>"
labels: ["positive vibes"]
assignees:
  - trip5
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to give feedback!
  - type: textarea
    id: info
    attributes:
      label: Information
      description: |
        A quick description and some sample letters would be good.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
